// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai;

import com.generic.core.annotation.Metadata;
import com.generic.core.annotation.ServiceClient;
import com.generic.core.http.Response;
import com.generic.core.http.exception.HttpResponseException;
import com.generic.core.http.models.RequestOptions;
import com.generic.core.models.BinaryData;
import com.openai.implementation.ImagesImpl;
import com.openai.implementation.MultipartFormDataHelper;
import com.openai.models.CreateImageEditRequest;
import com.openai.models.CreateImageRequest;
import com.openai.models.CreateImageVariationRequest;
import com.openai.models.ImagesResponse;
import java.util.Objects;

/**
 * Initializes a new instance of the synchronous OpenAIClient type.
 */
@ServiceClient(builder = OpenAIClientBuilder.class)
public final class ImagesClient {
    @Metadata(generated = true)
    private final ImagesImpl serviceClient;

    /**
     * Initializes an instance of ImagesClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Metadata(generated = true)
    ImagesClient(ImagesImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Creates an image given a prompt.
     * <p><strong>Request Body Schema</strong></p>
     * 
     * <pre>{@code
     * {
     *     prompt: String (Required)
     *     model: String(dall-e-2/dall-e-3) (Optional)
     *     n: Long (Optional)
     *     quality: String(standard/hd) (Optional)
     *     response_format: String(url/b64_json) (Optional)
     *     size: String(256x256/512x512/1024x1024/1792x1024/1024x1792) (Optional)
     *     style: String(vivid/natural) (Optional)
     *     user: String (Optional)
     * }
     * }</pre>
     * 
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>{@code
     * {
     *     created: long (Required)
     *     data (Required): [
     *          (Required){
     *             b64_json: byte[] (Optional)
     *             url: String (Optional)
     *             revised_prompt: String (Optional)
     *         }
     *     ]
     * }
     * }</pre>
     * 
     * @param image The image parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @Metadata(generated = true)
    public Response<BinaryData> createImageWithResponse(BinaryData image, RequestOptions requestOptions) {
        return this.serviceClient.createImageWithResponse(image, requestOptions);
    }

    /**
     * Creates an edited or extended image given an original image and a prompt.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>{@code
     * {
     *     created: long (Required)
     *     data (Required): [
     *          (Required){
     *             b64_json: byte[] (Optional)
     *             url: String (Optional)
     *             revised_prompt: String (Optional)
     *         }
     *     ]
     * }
     * }</pre>
     * 
     * @param image The image parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @Metadata(generated = true)
    Response<BinaryData> createImageEditWithResponse(BinaryData image, RequestOptions requestOptions) {
        // Protocol API requires serialization of parts with content-disposition and data, as operation 'createImageEdit' is 'multipart/form-data'
        return this.serviceClient.createImageEditWithResponse(image, requestOptions);
    }

    /**
     * Creates an edited or extended image given an original image and a prompt.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>{@code
     * {
     *     created: long (Required)
     *     data (Required): [
     *          (Required){
     *             b64_json: byte[] (Optional)
     *             url: String (Optional)
     *             revised_prompt: String (Optional)
     *         }
     *     ]
     * }
     * }</pre>
     * 
     * @param image The image parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the service returns an error.
     * @return the response.
     */
    @Metadata(generated = true)
    Response<BinaryData> createImageVariationWithResponse(BinaryData image, RequestOptions requestOptions) {
        // Protocol API requires serialization of parts with content-disposition and data, as operation 'createImageVariation' is 'multipart/form-data'
        return this.serviceClient.createImageVariationWithResponse(image, requestOptions);
    }

    /**
     * Creates an image given a prompt.
     * 
     * @param image The image parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(generated = true)
    public ImagesResponse createImage(CreateImageRequest image) {
        // Generated convenience method for createImageWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createImageWithResponse(BinaryData.fromObject(image), requestOptions).getValue()
            .toObject(ImagesResponse.class);
    }

    /**
     * Creates an edited or extended image given an original image and a prompt.
     * 
     * @param image The image parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(generated = true)
    public ImagesResponse createImageEdit(CreateImageEditRequest image) {
        // Generated convenience method for createImageEditWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createImageEditWithResponse(new MultipartFormDataHelper(requestOptions)
            .serializeFileField("image", image.getImage().getContent(), image.getImage().getContentType(),
                image.getImage().getFilename())
            .serializeTextField("prompt", image.getPrompt())
            .serializeFileField("mask", image.getMask() == null ? null : image.getMask().getContent(),
                image.getMask() == null ? null : image.getMask().getContentType(),
                image.getMask() == null ? null : image.getMask().getFilename())
            .serializeTextField("model", Objects.toString(image.getModel()))
            .serializeTextField("n", Objects.toString(image.getN()))
            .serializeTextField("size", Objects.toString(image.getSize()))
            .serializeTextField("response_format", Objects.toString(image.getResponseFormat()))
            .serializeTextField("user", image.getUser())
            .end()
            .getRequestBody(), requestOptions).getValue().toObject(ImagesResponse.class);
    }

    /**
     * Creates an edited or extended image given an original image and a prompt.
     * 
     * @param image The image parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the service returns an error.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Metadata(generated = true)
    public ImagesResponse createImageVariation(CreateImageVariationRequest image) {
        // Generated convenience method for createImageVariationWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createImageVariationWithResponse(new MultipartFormDataHelper(requestOptions)
            .serializeFileField("image", image.getImage().getContent(), image.getImage().getContentType(),
                image.getImage().getFilename())
            .serializeTextField("model", Objects.toString(image.getModel()))
            .serializeTextField("n", Objects.toString(image.getN()))
            .serializeTextField("response_format", Objects.toString(image.getResponseFormat()))
            .serializeTextField("size", Objects.toString(image.getSize()))
            .serializeTextField("user", image.getUser())
            .end()
            .getRequestBody(), requestOptions).getValue().toObject(ImagesResponse.class);
    }
}
