emit:
  - "@azure-tools/typespec-java"
options:
  "@azure-tools/typespec-java":
    emitter-output-dir: "{project-root}/tsp-output"
    flavor: "generic"
    namespace: "com.openai"
    dev-options:
      generate-code-model: true
      loglevel: info
