// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.annotation.TypeConditions;
import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * The ChatMessageContent model.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class ChatMessageContent implements JsonSerializable<ChatMessageContent> {
    /**
     * Creates an instance of ChatMessageContent class.
     */
    @Metadata(generated = true)
    public ChatMessageContent() {
    }

    /**
     * {@inheritDoc}
     */
    @Metadata(generated = true)
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of ChatMessageContent from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of ChatMessageContent if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IOException If an error occurs while reading the ChatMessageContent.
     */
    @Metadata(generated = true)
    public static ChatMessageContent fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            ChatMessageContent deserializedChatMessageContent = new ChatMessageContent();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                reader.skipChildren();
            }

            return deserializedChatMessageContent;
        });
    }
}
