// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

/**
 * Defines values for CreateChatCompletionStreamResponseChoiceFinishReason.
 */
public enum CreateChatCompletionStreamResponseChoiceFinishReason {
    /**
     * Enum value stop.
     */
    STOP("stop"),

    /**
     * Enum value length.
     */
    LENGTH("length"),

    /**
     * Enum value tool_calls.
     */
    TOOL_CALLS("tool_calls"),

    /**
     * Enum value content_filter.
     */
    CONTENT_FILTER("content_filter"),

    /**
     * Enum value function_call.
     */
    FUNCTION_CALL("function_call");

    /**
     * The actual serialized value for a CreateChatCompletionStreamResponseChoiceFinishReason instance.
     */
    private final String value;

    CreateChatCompletionStreamResponseChoiceFinishReason(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a CreateChatCompletionStreamResponseChoiceFinishReason instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed CreateChatCompletionStreamResponseChoiceFinishReason object, or null if unable to parse.
     */
    public static CreateChatCompletionStreamResponseChoiceFinishReason fromString(String value) {
        if (value == null) {
            return null;
        }
        CreateChatCompletionStreamResponseChoiceFinishReason[] items
            = CreateChatCompletionStreamResponseChoiceFinishReason.values();
        for (CreateChatCompletionStreamResponseChoiceFinishReason item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
