// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The CreateModerationRequestInput2 model.
 */
@Immutable
public final class CreateModerationRequestInput2 implements JsonSerializable<CreateModerationRequestInput2> {
    /*
     * Always `image_url`.
     */
    @Generated
    private final String type = "image_url";

    /*
     * Contains either an image URL or a data URL for a base64 encoded image.
     */
    @Generated
    private final CreateModerationRequestInputImageUrl imageUrl;

    /**
     * Creates an instance of CreateModerationRequestInput2 class.
     * 
     * @param imageUrl the imageUrl value to set.
     */
    @Generated
    public CreateModerationRequestInput2(CreateModerationRequestInputImageUrl imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * Get the type property: Always `image_url`.
     * 
     * @return the type value.
     */
    @Generated
    public String getType() {
        return this.type;
    }

    /**
     * Get the imageUrl property: Contains either an image URL or a data URL for a base64 encoded image.
     * 
     * @return the imageUrl value.
     */
    @Generated
    public CreateModerationRequestInputImageUrl getImageUrl() {
        return this.imageUrl;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("type", this.type);
        jsonWriter.writeJsonField("image_url", this.imageUrl);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of CreateModerationRequestInput2 from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of CreateModerationRequestInput2 if the JsonReader was pointing to an instance of it, or null
     * if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the CreateModerationRequestInput2.
     */
    @Generated
    public static CreateModerationRequestInput2 fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            CreateModerationRequestInputImageUrl imageUrl = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("image_url".equals(fieldName)) {
                    imageUrl = CreateModerationRequestInputImageUrl.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }
            return new CreateModerationRequestInput2(imageUrl);
        });
    }
}
