// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.util.ExpandableEnum;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Defines values for ListVectorStoreFilesFilter.
 */
public final class ListVectorStoreFilesFilter implements ExpandableEnum<String> {
    private static final Map<String, ListVectorStoreFilesFilter> VALUES = new ConcurrentHashMap<>();

    /**
     * Static value in_progress for ListVectorStoreFilesFilter.
     */
    @Metadata(generated = true)
    public static final ListVectorStoreFilesFilter IN_PROGRESS = fromString("in_progress");

    /**
     * Static value completed for ListVectorStoreFilesFilter.
     */
    @Metadata(generated = true)
    public static final ListVectorStoreFilesFilter COMPLETED = fromString("completed");

    /**
     * Static value failed for ListVectorStoreFilesFilter.
     */
    @Metadata(generated = true)
    public static final ListVectorStoreFilesFilter FAILED = fromString("failed");

    /**
     * Static value cancelled for ListVectorStoreFilesFilter.
     */
    @Metadata(generated = true)
    public static final ListVectorStoreFilesFilter CANCELLED = fromString("cancelled");

    private final String name;

    private ListVectorStoreFilesFilter(String name) {
        this.name = name;
    }

    /**
     * Creates or finds a ListVectorStoreFilesFilter.
     * 
     * @param name a name to look for.
     * @return the corresponding ListVectorStoreFilesFilter.
     */
    @Metadata(generated = true)
    public static ListVectorStoreFilesFilter fromString(String name) {
        if (name == null) {
            return null;
        }
        ListVectorStoreFilesFilter value = VALUES.get(name);
        if (value != null) {
            return value;
        }
        return VALUES.computeIfAbsent(name, key -> new ListVectorStoreFilesFilter(key));
    }

    /**
     * Gets the value of the ListVectorStoreFilesFilter instance.
     * 
     * @return the value of the ListVectorStoreFilesFilter instance.
     */
    @Metadata(generated = true)
    @Override
    public String getValue() {
        return this.name;
    }

    @Metadata(generated = true)
    @Override
    public String toString() {
        return name;
    }
}
