// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import com.azure.core.annotation.Generated;
import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Defines values for ListVectorStoreFilesFilter.
 */
public final class ListVectorStoreFilesFilter extends ExpandableStringEnum<ListVectorStoreFilesFilter> {
    /**
     * Static value in_progress for ListVectorStoreFilesFilter.
     */
    @Generated
    public static final ListVectorStoreFilesFilter IN_PROGRESS = fromString("in_progress");

    /**
     * Static value completed for ListVectorStoreFilesFilter.
     */
    @Generated
    public static final ListVectorStoreFilesFilter COMPLETED = fromString("completed");

    /**
     * Static value failed for ListVectorStoreFilesFilter.
     */
    @Generated
    public static final ListVectorStoreFilesFilter FAILED = fromString("failed");

    /**
     * Static value cancelled for ListVectorStoreFilesFilter.
     */
    @Generated
    public static final ListVectorStoreFilesFilter CANCELLED = fromString("cancelled");

    /**
     * Creates a new instance of ListVectorStoreFilesFilter value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Generated
    @Deprecated
    public ListVectorStoreFilesFilter() {
    }

    /**
     * Creates or finds a ListVectorStoreFilesFilter from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding ListVectorStoreFilesFilter.
     */
    @Generated
    public static ListVectorStoreFilesFilter fromString(String name) {
        return fromString(name, ListVectorStoreFilesFilter.class);
    }

    /**
     * Gets known ListVectorStoreFilesFilter values.
     * 
     * @return known ListVectorStoreFilesFilter values.
     */
    @Generated
    public static Collection<ListVectorStoreFilesFilter> values() {
        return values(ListVectorStoreFilesFilter.class);
    }
}
