// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The refusal content generated by the assistant.
 */
@Immutable
public final class MessageContentRefusalObject extends MessageContent {
    /*
     * Always `refusal`.
     */
    @Generated
    private final String type = "refusal";

    /*
     * The refusal property.
     */
    @Generated
    private final String refusal;

    /**
     * Creates an instance of MessageContentRefusalObject class.
     * 
     * @param refusal the refusal value to set.
     */
    @Generated
    public MessageContentRefusalObject(String refusal) {
        this.refusal = refusal;
    }

    /**
     * Get the type property: Always `refusal`.
     * 
     * @return the type value.
     */
    @Generated
    public String getType() {
        return this.type;
    }

    /**
     * Get the refusal property: The refusal property.
     * 
     * @return the refusal value.
     */
    @Generated
    public String getRefusal() {
        return this.refusal;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("type", this.type);
        jsonWriter.writeStringField("refusal", this.refusal);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of MessageContentRefusalObject from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of MessageContentRefusalObject if the JsonReader was pointing to an instance of it, or null
     * if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the MessageContentRefusalObject.
     */
    @Generated
    public static MessageContentRefusalObject fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String refusal = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("refusal".equals(fieldName)) {
                    refusal = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            return new MessageContentRefusalObject(refusal);
        });
    }
}
