// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

/**
 * Defines values for OpenAIFileStatus.
 */
public enum OpenAIFileStatus {
    /**
     * Enum value uploaded.
     */
    UPLOADED("uploaded"),

    /**
     * Enum value processed.
     */
    PROCESSED("processed"),

    /**
     * Enum value error.
     */
    ERROR("error");

    /**
     * The actual serialized value for a OpenAIFileStatus instance.
     */
    private final String value;

    OpenAIFileStatus(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a OpenAIFileStatus instance.
     * 
     * @param value the serialized value to parse.
     * @return the parsed OpenAIFileStatus object, or null if unable to parse.
     */
    public static OpenAIFileStatus fromString(String value) {
        if (value == null) {
            return null;
        }
        OpenAIFileStatus[] items = OpenAIFileStatus.values();
        for (OpenAIFileStatus item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return this.value;
    }
}
