// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.util.ExpandableEnum;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Defines values for RealtimeVoice.
 */
public final class RealtimeVoice implements ExpandableEnum<String> {
    private static final Map<String, RealtimeVoice> VALUES = new ConcurrentHashMap<>();

    /**
     * Static value alloy for RealtimeVoice.
     */
    @Metadata(generated = true)
    public static final RealtimeVoice ALLOY = fromString("alloy");

    /**
     * Static value shimmer for RealtimeVoice.
     */
    @Metadata(generated = true)
    public static final RealtimeVoice SHIMMER = fromString("shimmer");

    /**
     * Static value echo for RealtimeVoice.
     */
    @Metadata(generated = true)
    public static final RealtimeVoice ECHO = fromString("echo");

    private final String name;

    private RealtimeVoice(String name) {
        this.name = name;
    }

    /**
     * Creates or finds a RealtimeVoice.
     * 
     * @param name a name to look for.
     * @return the corresponding RealtimeVoice.
     */
    @Metadata(generated = true)
    public static RealtimeVoice fromString(String name) {
        if (name == null) {
            return null;
        }
        RealtimeVoice value = VALUES.get(name);
        if (value != null) {
            return value;
        }
        return VALUES.computeIfAbsent(name, key -> new RealtimeVoice(key));
    }

    /**
     * Gets the value of the RealtimeVoice instance.
     * 
     * @return the value of the RealtimeVoice instance.
     */
    @Metadata(generated = true)
    @Override
    public String getValue() {
        return this.name;
    }

    @Metadata(generated = true)
    @Override
    public String toString() {
        return name;
    }
}
