// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.util.ExpandableEnum;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Defines values for RealtimeAudioFormat.
 */
public final class RealtimeAudioFormat implements ExpandableEnum<String> {
    private static final Map<String, RealtimeAudioFormat> VALUES = new ConcurrentHashMap<>();

    /**
     * Static value pcm16 for RealtimeAudioFormat.
     */
    @Metadata(generated = true)
    public static final RealtimeAudioFormat PCM16 = fromString("pcm16");

    /**
     * Static value g711_ulaw for RealtimeAudioFormat.
     */
    @Metadata(generated = true)
    public static final RealtimeAudioFormat G711_ULAW = fromString("g711_ulaw");

    /**
     * Static value g711_alaw for RealtimeAudioFormat.
     */
    @Metadata(generated = true)
    public static final RealtimeAudioFormat G711_ALAW = fromString("g711_alaw");

    private final String name;

    private RealtimeAudioFormat(String name) {
        this.name = name;
    }

    /**
     * Creates or finds a RealtimeAudioFormat.
     * 
     * @param name a name to look for.
     * @return the corresponding RealtimeAudioFormat.
     */
    @Metadata(generated = true)
    public static RealtimeAudioFormat fromString(String name) {
        if (name == null) {
            return null;
        }
        RealtimeAudioFormat value = VALUES.get(name);
        if (value != null) {
            return value;
        }
        return VALUES.computeIfAbsent(name, key -> new RealtimeAudioFormat(key));
    }

    /**
     * Gets the value of the RealtimeAudioFormat instance.
     * 
     * @return the value of the RealtimeAudioFormat instance.
     */
    @Metadata(generated = true)
    @Override
    public String getValue() {
        return this.name;
    }

    @Metadata(generated = true)
    @Override
    public String toString() {
        return name;
    }
}
