// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.annotation.TypeConditions;
import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * The RealtimeAudioInputTranscriptionSettings model.
 */
@Metadata(conditions = { TypeConditions.FLUENT })
public final class RealtimeAudioInputTranscriptionSettings
    implements JsonSerializable<RealtimeAudioInputTranscriptionSettings> {
    /*
     * The model property.
     */
    @Metadata(generated = true)
    private RealtimeAudioInputTranscriptionModel model;

    /**
     * Creates an instance of RealtimeAudioInputTranscriptionSettings class.
     */
    @Metadata(generated = true)
    public RealtimeAudioInputTranscriptionSettings() {
    }

    /**
     * Get the model property: The model property.
     * 
     * @return the model value.
     */
    @Metadata(generated = true)
    public RealtimeAudioInputTranscriptionModel getModel() {
        return this.model;
    }

    /**
     * Set the model property: The model property.
     * 
     * @param model the model value to set.
     * @return the RealtimeAudioInputTranscriptionSettings object itself.
     */
    @Metadata(generated = true)
    public RealtimeAudioInputTranscriptionSettings setModel(RealtimeAudioInputTranscriptionModel model) {
        this.model = model;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Metadata(generated = true)
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("model", this.model == null ? null : this.model.toString());
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RealtimeAudioInputTranscriptionSettings from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of RealtimeAudioInputTranscriptionSettings if the JsonReader was pointing to an instance of
     * it, or null if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the RealtimeAudioInputTranscriptionSettings.
     */
    @Metadata(generated = true)
    public static RealtimeAudioInputTranscriptionSettings fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            RealtimeAudioInputTranscriptionSettings deserializedRealtimeAudioInputTranscriptionSettings
                = new RealtimeAudioInputTranscriptionSettings();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("model".equals(fieldName)) {
                    deserializedRealtimeAudioInputTranscriptionSettings.model
                        = RealtimeAudioInputTranscriptionModel.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedRealtimeAudioInputTranscriptionSettings;
        });
    }
}
