// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.annotation.TypeConditions;
import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * The RunStepDetailsToolCallsFunctionObjectFunction model.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class RunStepDetailsToolCallsFunctionObjectFunction
    implements JsonSerializable<RunStepDetailsToolCallsFunctionObjectFunction> {
    /*
     * The name of the function.
     */
    @Metadata(generated = true)
    private final String name;

    /*
     * The arguments passed to the function.
     */
    @Metadata(generated = true)
    private final String arguments;

    /*
     * The output of the function. This will be `null` if the outputs have not been
     * [submitted](/docs/api-reference/runs/submitToolOutputs) yet.
     */
    @Metadata(generated = true)
    private final String output;

    /**
     * Creates an instance of RunStepDetailsToolCallsFunctionObjectFunction class.
     * 
     * @param name the name value to set.
     * @param arguments the arguments value to set.
     * @param output the output value to set.
     */
    @Metadata(generated = true)
    private RunStepDetailsToolCallsFunctionObjectFunction(String name, String arguments, String output) {
        this.name = name;
        this.arguments = arguments;
        this.output = output;
    }

    /**
     * Get the name property: The name of the function.
     * 
     * @return the name value.
     */
    @Metadata(generated = true)
    public String getName() {
        return this.name;
    }

    /**
     * Get the arguments property: The arguments passed to the function.
     * 
     * @return the arguments value.
     */
    @Metadata(generated = true)
    public String getArguments() {
        return this.arguments;
    }

    /**
     * Get the output property: The output of the function. This will be `null` if the outputs have not been
     * [submitted](/docs/api-reference/runs/submitToolOutputs) yet.
     * 
     * @return the output value.
     */
    @Metadata(generated = true)
    public String getOutput() {
        return this.output;
    }

    /**
     * {@inheritDoc}
     */
    @Metadata(generated = true)
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("name", this.name);
        jsonWriter.writeStringField("arguments", this.arguments);
        jsonWriter.writeStringField("output", this.output);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of RunStepDetailsToolCallsFunctionObjectFunction from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of RunStepDetailsToolCallsFunctionObjectFunction if the JsonReader was pointing to an
     * instance of it, or null if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the RunStepDetailsToolCallsFunctionObjectFunction.
     */
    @Metadata(generated = true)
    public static RunStepDetailsToolCallsFunctionObjectFunction fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            String name = null;
            String arguments = null;
            String output = null;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("name".equals(fieldName)) {
                    name = reader.getString();
                } else if ("arguments".equals(fieldName)) {
                    arguments = reader.getString();
                } else if ("output".equals(fieldName)) {
                    output = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }
            return new RunStepDetailsToolCallsFunctionObjectFunction(name, arguments, output);
        });
    }
}
