// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.annotation.TypeConditions;
import io.clientcore.core.json.JsonReader;
import io.clientcore.core.json.JsonSerializable;
import io.clientcore.core.json.JsonToken;
import io.clientcore.core.json.JsonWriter;
import java.io.IOException;

/**
 * The SubmitToolOutputsRunRequestToolOutput model.
 */
@Metadata(conditions = { TypeConditions.FLUENT })
public final class SubmitToolOutputsRunRequestToolOutput
    implements JsonSerializable<SubmitToolOutputsRunRequestToolOutput> {
    /*
     * The ID of the tool call in the `required_action` object within the run object the output is being submitted for.
     */
    @Metadata(generated = true)
    private String toolCallId;

    /*
     * The output of the tool call to be submitted to continue the run.
     */
    @Metadata(generated = true)
    private String output;

    /**
     * Creates an instance of SubmitToolOutputsRunRequestToolOutput class.
     */
    @Metadata(generated = true)
    public SubmitToolOutputsRunRequestToolOutput() {
    }

    /**
     * Get the toolCallId property: The ID of the tool call in the `required_action` object within the run object the
     * output is being submitted for.
     * 
     * @return the toolCallId value.
     */
    @Metadata(generated = true)
    public String getToolCallId() {
        return this.toolCallId;
    }

    /**
     * Set the toolCallId property: The ID of the tool call in the `required_action` object within the run object the
     * output is being submitted for.
     * 
     * @param toolCallId the toolCallId value to set.
     * @return the SubmitToolOutputsRunRequestToolOutput object itself.
     */
    @Metadata(generated = true)
    public SubmitToolOutputsRunRequestToolOutput setToolCallId(String toolCallId) {
        this.toolCallId = toolCallId;
        return this;
    }

    /**
     * Get the output property: The output of the tool call to be submitted to continue the run.
     * 
     * @return the output value.
     */
    @Metadata(generated = true)
    public String getOutput() {
        return this.output;
    }

    /**
     * Set the output property: The output of the tool call to be submitted to continue the run.
     * 
     * @param output the output value to set.
     * @return the SubmitToolOutputsRunRequestToolOutput object itself.
     */
    @Metadata(generated = true)
    public SubmitToolOutputsRunRequestToolOutput setOutput(String output) {
        this.output = output;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Metadata(generated = true)
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("tool_call_id", this.toolCallId);
        jsonWriter.writeStringField("output", this.output);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of SubmitToolOutputsRunRequestToolOutput from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of SubmitToolOutputsRunRequestToolOutput if the JsonReader was pointing to an instance of it,
     * or null if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the SubmitToolOutputsRunRequestToolOutput.
     */
    @Metadata(generated = true)
    public static SubmitToolOutputsRunRequestToolOutput fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            SubmitToolOutputsRunRequestToolOutput deserializedSubmitToolOutputsRunRequestToolOutput
                = new SubmitToolOutputsRunRequestToolOutput();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("tool_call_id".equals(fieldName)) {
                    deserializedSubmitToolOutputsRunRequestToolOutput.toolCallId = reader.getString();
                } else if ("output".equals(fieldName)) {
                    deserializedSubmitToolOutputsRunRequestToolOutput.output = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedSubmitToolOutputsRunRequestToolOutput;
        });
    }
}
