emit:
  - "@typespec/openapi3"
  - "@typespec/http-client-java"
options:
  "@typespec/openapi3":
    output-file: "{project-root}/../.openapi3/openapi3-openai.yaml"
  "@typespec/http-client-java":
    output-dir: "{project-root}/../.java"
    namespace: "com.openai"
    enable-subclient: true
