// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai.models;

import com.generic.core.annotation.Metadata;
import com.generic.core.annotation.TypeConditions;
import com.generic.json.JsonReader;
import com.generic.json.JsonSerializable;
import com.generic.json.JsonToken;
import com.generic.json.JsonWriter;
import java.io.IOException;

/**
 * The EmbeddingUsage model.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class EmbeddingUsage implements JsonSerializable<EmbeddingUsage> {
    /*
     * The number of tokens used by the prompt.
     */
    @Metadata(generated = true)
    private final long promptTokens;

    /*
     * The total number of tokens used by the request.
     */
    @Metadata(generated = true)
    private final long totalTokens;

    /**
     * Creates an instance of EmbeddingUsage class.
     * 
     * @param promptTokens the promptTokens value to set.
     * @param totalTokens the totalTokens value to set.
     */
    @Metadata(generated = true)
    private EmbeddingUsage(long promptTokens, long totalTokens) {
        this.promptTokens = promptTokens;
        this.totalTokens = totalTokens;
    }

    /**
     * Get the promptTokens property: The number of tokens used by the prompt.
     * 
     * @return the promptTokens value.
     */
    @Metadata(generated = true)
    public long getPromptTokens() {
        return this.promptTokens;
    }

    /**
     * Get the totalTokens property: The total number of tokens used by the request.
     * 
     * @return the totalTokens value.
     */
    @Metadata(generated = true)
    public long getTotalTokens() {
        return this.totalTokens;
    }

    /**
     * {@inheritDoc}
     */
    @Metadata(generated = true)
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeLongField("prompt_tokens", this.promptTokens);
        jsonWriter.writeLongField("total_tokens", this.totalTokens);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of EmbeddingUsage from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of EmbeddingUsage if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the EmbeddingUsage.
     */
    @Metadata(generated = true)
    public static EmbeddingUsage fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            long promptTokens = 0L;
            long totalTokens = 0L;
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("prompt_tokens".equals(fieldName)) {
                    promptTokens = reader.getLong();
                } else if ("total_tokens".equals(fieldName)) {
                    totalTokens = reader.getLong();
                } else {
                    reader.skipChildren();
                }
            }
            return new EmbeddingUsage(promptTokens, totalTokens);
        });
    }
}
