// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;
import com.azure.core.util.FluxUtil;
import com.openai.implementation.AudioImpl;
import com.openai.implementation.MultipartFormDataHelper;
import com.openai.models.CreateSpeechRequest;
import com.openai.models.CreateTranscriptionRequest;
import com.openai.models.CreateTranslationRequest;
import java.util.Objects;
import reactor.core.publisher.Mono;

/**
 * Initializes a new instance of the asynchronous Audio type.
 */
@ServiceClient(builder = OpenAIClientBuilder.class, isAsync = true)
public final class AudioAsyncClient {
    @Generated
    private final AudioImpl serviceClient;

    /**
     * Initializes an instance of AudioAsyncClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Generated
    AudioAsyncClient(AudioImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Generates audio from the input text.
     * <p><strong>Request Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     model: String(tts-1/tts-1-hd) (Required)
     *     input: String (Required)
     *     voice: String(alloy/echo/fable/onyx/nova/shimmer) (Required)
     *     response_format: String(mp3/opus/aac/flac/wav/pcm) (Optional)
     *     speed: Double (Optional)
     * }
     * }
     * </pre>
     * 
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * BinaryData
     * }
     * </pre>
     * 
     * @param requestBody The requestBody parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<Response<BinaryData>> createSpeechWithResponse(BinaryData requestBody, RequestOptions requestOptions) {
        return this.serviceClient.createSpeechWithResponseAsync(requestBody, requestOptions);
    }

    /**
     * Transcribes audio into the input language.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * String
     * }
     * </pre>
     * 
     * @param requestBody The requestBody parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return a sequence of textual characters along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    Mono<Response<BinaryData>> createTranscriptionWithResponse(BinaryData requestBody, RequestOptions requestOptions) {
        // Protocol API requires serialization of parts with content-disposition and data, as operation
        // 'createTranscription' is 'multipart/form-data'
        return this.serviceClient.createTranscriptionWithResponseAsync(requestBody, requestOptions);
    }

    /**
     * Translates audio into English..
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * String
     * }
     * </pre>
     * 
     * @param requestBody The requestBody parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return a sequence of textual characters along with {@link Response} on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    Mono<Response<BinaryData>> createTranslationWithResponse(BinaryData requestBody, RequestOptions requestOptions) {
        // Protocol API requires serialization of parts with content-disposition and data, as operation
        // 'createTranslation' is 'multipart/form-data'
        return this.serviceClient.createTranslationWithResponseAsync(requestBody, requestOptions);
    }

    /**
     * Generates audio from the input text.
     * 
     * @param requestBody The requestBody parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response body on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<BinaryData> createSpeech(CreateSpeechRequest requestBody) {
        // Generated convenience method for createSpeechWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createSpeechWithResponse(BinaryData.fromObject(requestBody), requestOptions).flatMap(FluxUtil::toMono);
    }

    /**
     * Transcribes audio into the input language.
     * 
     * @param requestBody The requestBody parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a sequence of textual characters on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<String> createTranscription(CreateTranscriptionRequest requestBody) {
        // Generated convenience method for createTranscriptionWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createTranscriptionWithResponse(new MultipartFormDataHelper(requestOptions)
            .serializeFileField("file", requestBody.getFile().getContent(), requestBody.getFile().getContentType(),
                requestBody.getFile().getFilename())
            .serializeTextField("model", Objects.toString(requestBody.getModel()))
            .serializeTextField("language", requestBody.getLanguage())
            .serializeTextField("prompt", requestBody.getPrompt())
            .serializeTextField("response_format", Objects.toString(requestBody.getResponseFormat()))
            .serializeTextField("temperature", Objects.toString(requestBody.getTemperature()))
            .serializeJsonField("timestamp_granularities[]", requestBody.getTimestampGranularities())
            .end()
            .getRequestBody(), requestOptions).flatMap(FluxUtil::toMono)
                .map(protocolMethodData -> protocolMethodData.toObject(String.class));
    }

    /**
     * Translates audio into English..
     * 
     * @param requestBody The requestBody parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a sequence of textual characters on successful completion of {@link Mono}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Mono<String> createTranslation(CreateTranslationRequest requestBody) {
        // Generated convenience method for createTranslationWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createTranslationWithResponse(new MultipartFormDataHelper(requestOptions)
            .serializeFileField("file", requestBody.getFile().getContent(), requestBody.getFile().getContentType(),
                requestBody.getFile().getFilename())
            .serializeTextField("model", Objects.toString(requestBody.getModel()))
            .serializeTextField("prompt", requestBody.getPrompt())
            .serializeTextField("response_format", Objects.toString(requestBody.getResponseFormat()))
            .serializeTextField("temperature", Objects.toString(requestBody.getTemperature()))
            .end()
            .getRequestBody(), requestOptions).flatMap(FluxUtil::toMono)
                .map(protocolMethodData -> protocolMethodData.toObject(String.class));
    }
}
