// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.openai;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceClient;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.exception.ClientAuthenticationException;
import com.azure.core.exception.HttpResponseException;
import com.azure.core.exception.ResourceModifiedException;
import com.azure.core.exception.ResourceNotFoundException;
import com.azure.core.http.rest.RequestOptions;
import com.azure.core.http.rest.Response;
import com.azure.core.util.BinaryData;
import com.openai.implementation.FineTuningImpl;
import com.openai.models.CreateFineTuningJobRequest;
import com.openai.models.FineTuningJob;
import com.openai.models.ListFineTuningJobCheckpointsResponse;
import com.openai.models.ListFineTuningJobEventsResponse;
import com.openai.models.ListPaginatedFineTuningJobsResponse;

/**
 * Initializes a new instance of the synchronous FineTuning type.
 */
@ServiceClient(builder = OpenAIClientBuilder.class)
public final class FineTuningClient {
    @Generated
    private final FineTuningImpl serviceClient;

    /**
     * Initializes an instance of FineTuningClient class.
     * 
     * @param serviceClient the service client implementation.
     */
    @Generated
    FineTuningClient(FineTuningImpl serviceClient) {
        this.serviceClient = serviceClient;
    }

    /**
     * Creates a fine-tuning job which begins the process of creating a new model from a given dataset.
     * 
     * Response includes details of the enqueued job including job status and the name of the fine-tuned models once
     * complete.
     * 
     * [Learn more about fine-tuning](/docs/guides/fine-tuning).
     * <p><strong>Request Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     model: String(babbage-002/davinci-002/gpt-3.5-turbo/gpt-4o-mini) (Required)
     *     training_file: String (Required)
     *     hyperparameters (Optional): {
     *         n_epochs: BinaryData (Optional)
     *         batch_size: BinaryData (Optional)
     *         learning_rate_multiplier: BinaryData (Optional)
     *     }
     *     suffix: String (Optional)
     *     validation_file: String (Optional)
     *     integrations (Optional): [
     *          (Optional){
     *             type: String (Required)
     *         }
     *     ]
     *     seed: Integer (Optional)
     * }
     * }
     * </pre>
     * 
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     user_provided_suffix: String (Optional)
     *     id: String (Required)
     *     created_at: long (Required)
     *     error (Required): {
     *         code: String (Required)
     *         message: String (Required)
     *         param: String (Required)
     *     }
     *     fine_tuned_model: String (Required)
     *     finished_at: Long (Required)
     *     hyperparameters (Required): {
     *         n_epochs: BinaryData (Required)
     *         batch_size: BinaryData (Required)
     *         learning_rate_multiplier: BinaryData (Required)
     *     }
     *     model: String (Required)
     *     object: String (Required)
     *     organization_id: String (Required)
     *     result_files (Required): [
     *         String (Required)
     *     ]
     *     status: String(validating_files/queued/running/succeeded/failed/cancelled) (Required)
     *     trained_tokens: Integer (Required)
     *     training_file: String (Required)
     *     validation_file: String (Required)
     *     integrations (Optional): [
     *          (Optional){
     *             type: String (Required)
     *         }
     *     ]
     *     seed: int (Required)
     *     estimated_finish: Long (Optional)
     * }
     * }
     * </pre>
     * 
     * @param requestBody The requestBody parameter.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the `fine_tuning.job` object represents a fine-tuning job that has been created through the API along
     * with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> createFineTuningJobWithResponse(BinaryData requestBody, RequestOptions requestOptions) {
        return this.serviceClient.createFineTuningJobWithResponse(requestBody, requestOptions);
    }

    /**
     * List your organization's fine-tuning jobs.
     * <p><strong>Query Parameters</strong></p>
     * <table border="1">
     * <caption>Query Parameters</caption>
     * <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     * <tr><td>after</td><td>String</td><td>No</td><td>Identifier for the last job from the previous pagination
     * request.</td></tr>
     * <tr><td>limit</td><td>Integer</td><td>No</td><td>Number of fine-tuning jobs to retrieve.</td></tr>
     * </table>
     * You can add these to a request with {@link RequestOptions#addQueryParam}
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     data (Required): [
     *          (Required){
     *             user_provided_suffix: String (Optional)
     *             id: String (Required)
     *             created_at: long (Required)
     *             error (Required): {
     *                 code: String (Required)
     *                 message: String (Required)
     *                 param: String (Required)
     *             }
     *             fine_tuned_model: String (Required)
     *             finished_at: Long (Required)
     *             hyperparameters (Required): {
     *                 n_epochs: BinaryData (Required)
     *                 batch_size: BinaryData (Required)
     *                 learning_rate_multiplier: BinaryData (Required)
     *             }
     *             model: String (Required)
     *             object: String (Required)
     *             organization_id: String (Required)
     *             result_files (Required): [
     *                 String (Required)
     *             ]
     *             status: String(validating_files/queued/running/succeeded/failed/cancelled) (Required)
     *             trained_tokens: Integer (Required)
     *             training_file: String (Required)
     *             validation_file: String (Required)
     *             integrations (Optional): [
     *                  (Optional){
     *                     type: String (Required)
     *                 }
     *             ]
     *             seed: int (Required)
     *             estimated_finish: Long (Optional)
     *         }
     *     ]
     *     has_more: boolean (Required)
     *     object: String (Required)
     * }
     * }
     * </pre>
     * 
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> listPaginatedFineTuningJobsWithResponse(RequestOptions requestOptions) {
        return this.serviceClient.listPaginatedFineTuningJobsWithResponse(requestOptions);
    }

    /**
     * Get info about a fine-tuning job.
     * 
     * [Learn more about fine-tuning](/docs/guides/fine-tuning).
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     user_provided_suffix: String (Optional)
     *     id: String (Required)
     *     created_at: long (Required)
     *     error (Required): {
     *         code: String (Required)
     *         message: String (Required)
     *         param: String (Required)
     *     }
     *     fine_tuned_model: String (Required)
     *     finished_at: Long (Required)
     *     hyperparameters (Required): {
     *         n_epochs: BinaryData (Required)
     *         batch_size: BinaryData (Required)
     *         learning_rate_multiplier: BinaryData (Required)
     *     }
     *     model: String (Required)
     *     object: String (Required)
     *     organization_id: String (Required)
     *     result_files (Required): [
     *         String (Required)
     *     ]
     *     status: String(validating_files/queued/running/succeeded/failed/cancelled) (Required)
     *     trained_tokens: Integer (Required)
     *     training_file: String (Required)
     *     validation_file: String (Required)
     *     integrations (Optional): [
     *          (Optional){
     *             type: String (Required)
     *         }
     *     ]
     *     seed: int (Required)
     *     estimated_finish: Long (Optional)
     * }
     * }
     * </pre>
     * 
     * @param fineTuningJobId The ID of the fine-tuning job.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return info about a fine-tuning job.
     * 
     * [Learn more about fine-tuning](/docs/guides/fine-tuning) along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> retrieveFineTuningJobWithResponse(String fineTuningJobId,
        RequestOptions requestOptions) {
        return this.serviceClient.retrieveFineTuningJobWithResponse(fineTuningJobId, requestOptions);
    }

    /**
     * Immediately cancel a fine-tune job.
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     user_provided_suffix: String (Optional)
     *     id: String (Required)
     *     created_at: long (Required)
     *     error (Required): {
     *         code: String (Required)
     *         message: String (Required)
     *         param: String (Required)
     *     }
     *     fine_tuned_model: String (Required)
     *     finished_at: Long (Required)
     *     hyperparameters (Required): {
     *         n_epochs: BinaryData (Required)
     *         batch_size: BinaryData (Required)
     *         learning_rate_multiplier: BinaryData (Required)
     *     }
     *     model: String (Required)
     *     object: String (Required)
     *     organization_id: String (Required)
     *     result_files (Required): [
     *         String (Required)
     *     ]
     *     status: String(validating_files/queued/running/succeeded/failed/cancelled) (Required)
     *     trained_tokens: Integer (Required)
     *     training_file: String (Required)
     *     validation_file: String (Required)
     *     integrations (Optional): [
     *          (Optional){
     *             type: String (Required)
     *         }
     *     ]
     *     seed: int (Required)
     *     estimated_finish: Long (Optional)
     * }
     * }
     * </pre>
     * 
     * @param fineTuningJobId The ID of the fine-tuning job to cancel.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the `fine_tuning.job` object represents a fine-tuning job that has been created through the API along
     * with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> cancelFineTuningJobWithResponse(String fineTuningJobId, RequestOptions requestOptions) {
        return this.serviceClient.cancelFineTuningJobWithResponse(fineTuningJobId, requestOptions);
    }

    /**
     * List the checkpoints for a fine-tuning job.
     * <p><strong>Query Parameters</strong></p>
     * <table border="1">
     * <caption>Query Parameters</caption>
     * <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     * <tr><td>after</td><td>String</td><td>No</td><td>Identifier for the last checkpoint ID from the previous
     * pagination request.</td></tr>
     * <tr><td>limit</td><td>Integer</td><td>No</td><td>Number of checkpoints to retrieve.</td></tr>
     * </table>
     * You can add these to a request with {@link RequestOptions#addQueryParam}
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     data (Required): [
     *          (Required){
     *             id: String (Required)
     *             created_at: long (Required)
     *             fine_tuned_model_checkpoint: String (Required)
     *             step_number: int (Required)
     *             metrics (Required): {
     *                 step: Double (Optional)
     *                 train_loss: Double (Optional)
     *                 train_mean_token_accuracy: Double (Optional)
     *                 valid_loss: Double (Optional)
     *                 valid_mean_token_accuracy: Double (Optional)
     *                 full_valid_loss: Double (Optional)
     *                 full_valid_mean_token_accuracy: Double (Optional)
     *             }
     *             fine_tuning_job_id: String (Required)
     *             object: String (Required)
     *         }
     *     ]
     *     object: String (Required)
     *     first_id: String (Optional)
     *     last_id: String (Optional)
     *     has_more: boolean (Required)
     * }
     * }
     * </pre>
     * 
     * @param fineTuningJobId The ID of the fine-tuning job to get checkpoints for.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return the response body along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> listFineTuningJobCheckpointsWithResponse(String fineTuningJobId,
        RequestOptions requestOptions) {
        return this.serviceClient.listFineTuningJobCheckpointsWithResponse(fineTuningJobId, requestOptions);
    }

    /**
     * Get status updates for a fine-tuning job.
     * <p><strong>Query Parameters</strong></p>
     * <table border="1">
     * <caption>Query Parameters</caption>
     * <tr><th>Name</th><th>Type</th><th>Required</th><th>Description</th></tr>
     * <tr><td>after</td><td>String</td><td>No</td><td>Identifier for the last event from the previous pagination
     * request.</td></tr>
     * <tr><td>limit</td><td>Integer</td><td>No</td><td>Number of events to retrieve.</td></tr>
     * </table>
     * You can add these to a request with {@link RequestOptions#addQueryParam}
     * <p><strong>Response Body Schema</strong></p>
     * 
     * <pre>
     * {@code
     * {
     *     has_more: boolean (Required)
     *     data (Required): [
     *          (Required){
     *             id: String (Required)
     *             created_at: long (Required)
     *             level: String(info/warn/error) (Required)
     *             message: String (Required)
     *             object: String (Required)
     *         }
     *     ]
     *     object: String (Required)
     * }
     * }
     * </pre>
     * 
     * @param fineTuningJobId The ID of the fine-tuning job to get events for.
     * @param requestOptions The options to configure the HTTP request before HTTP client sends it.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @return status updates for a fine-tuning job along with {@link Response}.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<BinaryData> listFineTuningEventsWithResponse(String fineTuningJobId,
        RequestOptions requestOptions) {
        return this.serviceClient.listFineTuningEventsWithResponse(fineTuningJobId, requestOptions);
    }

    /**
     * Creates a fine-tuning job which begins the process of creating a new model from a given dataset.
     * 
     * Response includes details of the enqueued job including job status and the name of the fine-tuned models once
     * complete.
     * 
     * [Learn more about fine-tuning](/docs/guides/fine-tuning).
     * 
     * @param requestBody The requestBody parameter.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the `fine_tuning.job` object represents a fine-tuning job that has been created through the API.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public FineTuningJob createFineTuningJob(CreateFineTuningJobRequest requestBody) {
        // Generated convenience method for createFineTuningJobWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return createFineTuningJobWithResponse(BinaryData.fromObject(requestBody), requestOptions).getValue()
            .toObject(FineTuningJob.class);
    }

    /**
     * List your organization's fine-tuning jobs.
     * 
     * @param after Identifier for the last job from the previous pagination request.
     * @param limit Number of fine-tuning jobs to retrieve.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public ListPaginatedFineTuningJobsResponse listPaginatedFineTuningJobs(String after, Integer limit) {
        // Generated convenience method for listPaginatedFineTuningJobsWithResponse
        RequestOptions requestOptions = new RequestOptions();
        if (after != null) {
            requestOptions.addQueryParam("after", after, false);
        }
        if (limit != null) {
            requestOptions.addQueryParam("limit", String.valueOf(limit), false);
        }
        return listPaginatedFineTuningJobsWithResponse(requestOptions).getValue()
            .toObject(ListPaginatedFineTuningJobsResponse.class);
    }

    /**
     * List your organization's fine-tuning jobs.
     * 
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public ListPaginatedFineTuningJobsResponse listPaginatedFineTuningJobs() {
        // Generated convenience method for listPaginatedFineTuningJobsWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return listPaginatedFineTuningJobsWithResponse(requestOptions).getValue()
            .toObject(ListPaginatedFineTuningJobsResponse.class);
    }

    /**
     * Get info about a fine-tuning job.
     * 
     * [Learn more about fine-tuning](/docs/guides/fine-tuning).
     * 
     * @param fineTuningJobId The ID of the fine-tuning job.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return info about a fine-tuning job.
     * 
     * [Learn more about fine-tuning](/docs/guides/fine-tuning).
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public FineTuningJob retrieveFineTuningJob(String fineTuningJobId) {
        // Generated convenience method for retrieveFineTuningJobWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return retrieveFineTuningJobWithResponse(fineTuningJobId, requestOptions).getValue()
            .toObject(FineTuningJob.class);
    }

    /**
     * Immediately cancel a fine-tune job.
     * 
     * @param fineTuningJobId The ID of the fine-tuning job to cancel.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the `fine_tuning.job` object represents a fine-tuning job that has been created through the API.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public FineTuningJob cancelFineTuningJob(String fineTuningJobId) {
        // Generated convenience method for cancelFineTuningJobWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return cancelFineTuningJobWithResponse(fineTuningJobId, requestOptions).getValue()
            .toObject(FineTuningJob.class);
    }

    /**
     * List the checkpoints for a fine-tuning job.
     * 
     * @param fineTuningJobId The ID of the fine-tuning job to get checkpoints for.
     * @param after Identifier for the last checkpoint ID from the previous pagination request.
     * @param limit Number of checkpoints to retrieve.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public ListFineTuningJobCheckpointsResponse listFineTuningJobCheckpoints(String fineTuningJobId, String after,
        Integer limit) {
        // Generated convenience method for listFineTuningJobCheckpointsWithResponse
        RequestOptions requestOptions = new RequestOptions();
        if (after != null) {
            requestOptions.addQueryParam("after", after, false);
        }
        if (limit != null) {
            requestOptions.addQueryParam("limit", String.valueOf(limit), false);
        }
        return listFineTuningJobCheckpointsWithResponse(fineTuningJobId, requestOptions).getValue()
            .toObject(ListFineTuningJobCheckpointsResponse.class);
    }

    /**
     * List the checkpoints for a fine-tuning job.
     * 
     * @param fineTuningJobId The ID of the fine-tuning job to get checkpoints for.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the response.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public ListFineTuningJobCheckpointsResponse listFineTuningJobCheckpoints(String fineTuningJobId) {
        // Generated convenience method for listFineTuningJobCheckpointsWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return listFineTuningJobCheckpointsWithResponse(fineTuningJobId, requestOptions).getValue()
            .toObject(ListFineTuningJobCheckpointsResponse.class);
    }

    /**
     * Get status updates for a fine-tuning job.
     * 
     * @param fineTuningJobId The ID of the fine-tuning job to get events for.
     * @param after Identifier for the last event from the previous pagination request.
     * @param limit Number of events to retrieve.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return status updates for a fine-tuning job.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public ListFineTuningJobEventsResponse listFineTuningEvents(String fineTuningJobId, String after, Integer limit) {
        // Generated convenience method for listFineTuningEventsWithResponse
        RequestOptions requestOptions = new RequestOptions();
        if (after != null) {
            requestOptions.addQueryParam("after", after, false);
        }
        if (limit != null) {
            requestOptions.addQueryParam("limit", String.valueOf(limit), false);
        }
        return listFineTuningEventsWithResponse(fineTuningJobId, requestOptions).getValue()
            .toObject(ListFineTuningJobEventsResponse.class);
    }

    /**
     * Get status updates for a fine-tuning job.
     * 
     * @param fineTuningJobId The ID of the fine-tuning job to get events for.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws HttpResponseException thrown if the request is rejected by server.
     * @throws ClientAuthenticationException thrown if the request is rejected by server on status code 401.
     * @throws ResourceNotFoundException thrown if the request is rejected by server on status code 404.
     * @throws ResourceModifiedException thrown if the request is rejected by server on status code 409.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return status updates for a fine-tuning job.
     */
    @Generated
    @ServiceMethod(returns = ReturnType.SINGLE)
    public ListFineTuningJobEventsResponse listFineTuningEvents(String fineTuningJobId) {
        // Generated convenience method for listFineTuningEventsWithResponse
        RequestOptions requestOptions = new RequestOptions();
        return listFineTuningEventsWithResponse(fineTuningJobId, requestOptions).getValue()
            .toObject(ListFineTuningJobEventsResponse.class);
    }
}
